name: CI - ACS
on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '**.md'

jobs:
  build:
    env:
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install locally
        run: |
          sudo apt-get install -y python3-setuptools
          pip3 install -e .
      
      - name: run pipelines/acs
        run: python3 pipelines/acs/build.py
      
