name: CI - ACS
on:
  push:
    branches: [ main ]
    paths-ignore: 
      - '**.md'

jobs:
  build:
    env:
      API_KEY: ${{ secrets.API_KEY }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install locally
        run: |
          sudo apt-get install -y python3-setuptools
          pip3 install -e .
      
      - name: run economic
        run: python3 pipelines/acs/build.py economic

      - name: run demographic
        run: python3 pipelines/acs/build.py demographic

      - name: run housing
        run: python3 pipelines/acs/build.py housing

      - name: run social
        run: python3 pipelines/acs/build.py social
      
      - name: combine domains
        run: |
            cat pff_acs_economic.csv > pff_acs.csv
            tail -n +2 pff_acs_demographic.csv >> pff_acs.csv
            tail -n +2 pff_acs_housing.csv >> pff_acs.csv
            tail -n +2 pff_acs_social.csv >> pff_acs.csv

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: pff_acs.csv
          retention-days: 2
          
      - name: send to database
        run: |
          psql $EDM_DATA -c "
          DROP TABLE IF EXISTS pff_acs.\"2018-test\";
          CREATE TABLE pff_acs.\"2018-test\" (
              census_geoid text,
              pff_variable text,
              geotype text,
              c double precision,
              e double precision,
              m double precision,
              p double precision,
              z double precision,
              domain text
          );
          "
          cat pff_acs.csv | psql $EDM_DATA -c "
            COPY pff_acs.\"2018-test\" FROM STDIN DELIMITER ',' CSV HEADER;
          "
